// <auto-generated />
using System;
using Fazenda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221024001514_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fazenda.Domain.Entities.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnimal"), 1L, 1);

                    b.Property<string>("DescricaoAnimal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdAnimal");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Fazenda.Domain.Entities.CompraGado", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"), 1L, 1);

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPecuarista")
                        .HasColumnType("int");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdPecuarista");

                    b.ToTable("CompraGado");
                });

            modelBuilder.Entity("Fazenda.Domain.Entities.CompraGadoItem", b =>
                {
                    b.Property<int>("IdCompraGadoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraGadoItem"), 1L, 1);

                    b.Property<int?>("AnimalIdAnimal1")
                        .HasColumnType("int");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("int");

                    b.Property<int>("IdCompraGado")
                        .HasColumnType("int");

                    b.Property<int?>("Quantidade")
                        .IsRequired()
                        .HasMaxLength(999)
                        .HasColumnType("int");

                    b.HasKey("IdCompraGadoItem");

                    b.HasIndex("AnimalIdAnimal1");

                    b.HasIndex("IdAnimal");

                    b.HasIndex("IdCompraGado");

                    b.ToTable("CompraGadoItem");
                });

            modelBuilder.Entity("Fazenda.Domain.Entities.Pecuarista", b =>
                {
                    b.Property<int>("IdPecuarista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPecuarista"), 1L, 1);

                    b.Property<string>("NomePecuarista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPecuarista");

                    b.ToTable("Pecuarista");
                });

            modelBuilder.Entity("Fazenda.Domain.Entities.CompraGado", b =>
                {
                    b.HasOne("Fazenda.Domain.Entities.Pecuarista", "Pecuarista")
                        .WithMany("CompraGados")
                        .HasForeignKey("IdPecuarista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pecuarista");
                });

            modelBuilder.Entity("Fazenda.Domain.Entities.CompraGadoItem", b =>
                {
                    b.HasOne("Fazenda.Domain.Entities.Animal", null)
                        .WithMany("CompraGadoItems")
                        .HasForeignKey("AnimalIdAnimal1");

                    b.HasOne("Fazenda.Domain.Entities.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fazenda.Domain.Entities.CompraGado", "CompraGado")
                        .WithMany()
                        .HasForeignKey("IdCompraGado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("CompraGado");
                });

            modelBuilder.Entity("Fazenda.Domain.Entities.Animal", b =>
                {
                    b.Navigation("CompraGadoItems");
                });

            modelBuilder.Entity("Fazenda.Domain.Entities.Pecuarista", b =>
                {
                    b.Navigation("CompraGados");
                });
#pragma warning restore 612, 618
        }
    }
}
