// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_Fazenda.Context;

#nullable disable

namespace Project_Fazenda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project_Fazenda.Models.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnimal"));

                    b.Property<string>("DescricaoAnimal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.HasKey("IdAnimal");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("Project_Fazenda.Models.CompraGado", b =>
                {
                    b.Property<int>("IdCompra")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPecuarista")
                        .HasColumnType("integer");

                    b.HasKey("IdCompra");

                    b.ToTable("CompraGado");
                });

            modelBuilder.Entity("Project_Fazenda.Models.CompraGadoEm", b =>
                {
                    b.Property<int>("IdCompraEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompraEm"));

                    b.Property<int?>("CompraGadoIdCompra")
                        .HasColumnType("integer");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<int>("IdCompraGado")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantidade")
                        .IsRequired()
                        .HasMaxLength(999)
                        .HasColumnType("integer");

                    b.HasKey("IdCompraEm");

                    b.HasIndex("CompraGadoIdCompra");

                    b.HasIndex("IdAnimal");

                    b.ToTable("CompraGadoEm");
                });

            modelBuilder.Entity("Project_Fazenda.Models.Pecuarista", b =>
                {
                    b.Property<int>("IdPecuarista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPecuarista"));

                    b.Property<string>("NomePecuarista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPecuarista");

                    b.ToTable("Pecuarista");
                });

            modelBuilder.Entity("Project_Fazenda.Models.CompraGado", b =>
                {
                    b.HasOne("Project_Fazenda.Models.Pecuarista", "Pecuarista")
                        .WithMany("CompraGados")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pecuarista");
                });

            modelBuilder.Entity("Project_Fazenda.Models.CompraGadoEm", b =>
                {
                    b.HasOne("Project_Fazenda.Models.CompraGado", "CompraGado")
                        .WithMany()
                        .HasForeignKey("CompraGadoIdCompra");

                    b.HasOne("Project_Fazenda.Models.Animal", "Animal")
                        .WithMany("CompraGadoEms")
                        .HasForeignKey("IdAnimal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("CompraGado");
                });

            modelBuilder.Entity("Project_Fazenda.Models.Animal", b =>
                {
                    b.Navigation("CompraGadoEms");
                });

            modelBuilder.Entity("Project_Fazenda.Models.Pecuarista", b =>
                {
                    b.Navigation("CompraGados");
                });
#pragma warning restore 612, 618
        }
    }
}
